### ISSUE TITLE
[BUG]  No clear way of exiting the music application

### ISSUE THREAD

**Issue by msmick** [NeonGeckoCom/skill-free_music_archive#11]
### Description

There is no clear method or command of exiting the music player application and returning to the main Neon dashboard clock screen (on mycroft II device). 

### Other Notes

this may just be a documentation flaw but after trying numerous voice commands such as "cancel music" "exit music" "turn off music", "exit player" "exit music player" nothing so far has worked.

**Comment by NeonDaniel** [comment]
Transferring this issue to OCP, where the player logic is implemented
